apiVersion: apps/v1
kind: Deployment
metadata:
  name: canada-app
  namespace: backend-dev        # Change to backend-prod when needed
  labels:
    app: canada
spec:
  replicas: 2                   # Number of pods
  selector:
    matchLabels:
      app: canada
  template:
    metadata:
      labels:
        app: canada
    spec:
      containers:
      - name: canada
        image: aorko16/canada:latest     # Your Docker Hub image
        ports:
        - containerPort: 80              # Nginx default port
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        imagePullPolicy: Always
