apiVersion: v1
kind: Namespace
metadata:
  name: backend-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canada-app 
  namespace: backend-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canada
  template:
    metadata:
      labels:
        app: canada
    spec:
      containers:
        - name: canada
          image: aorko16/bangla:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: canada-service
  namespace: backend-dev
spec:
  selector:
    app: canada
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP      # Change to LoadBalancer if you want external access


