apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: frontend-team
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/aorko16/Gitops-Argocd.git
  destinations:
    - namespace: backend-dev
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canada-app
  namespace: argocd
spec:
  project: frontend-team
  source:
    repoURL: https://github.com/aorko16/Gitops-Argocd.git
    targetRevision: main
    path: k8s              # ✅ Changed from 'canada' → 'k8s'
  destination:
    server: https://kubernetes.default.svc
    namespace: backend-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
